### ISSUE TITLE
missing files in src/utils

### ISSUE THREAD

**Issue by e0397123** [jderiu/metric-robustness#1]
Dear Jan,

Great work on probing the robustness of trained metrics! 

I am trying to run your code, but I notice that several files are missing:

the dialogue_system_wrapper.py in the src/utils folder; the evaluate_metrics module in the src folder; and the analyse_outputs module in the src/utils folder. Is it possible to share with me these files? Thanks a lot.

**Comment by jderiu** [comment]
Thanks a lot for letting me know! I added the missing files. Let me know if it works now.

**Comment by e0397123** [comment]
Thanks a lot, I will try and let you know.

**Comment by e0397123** [comment]
Hi Jan, thanks, the code works perfectly.
